from typing import Any

EXCLUDED_EVENT_FIELDS: tuple[str, ...]
SIGNATURE_ALGORITHMS: tuple[str, ...]

def signing_payload(event: dict[str, Any]) -> dict[str, Any]: ...
def evidence_seal_hash(payload: Any, evidence_manifest: Any) -> str: ...
def sign(payload: Any, *, algorithm: str, key: bytes) -> str: ...
def verify(payload: Any, value: str, *, algorithm: str, key: bytes) -> bool: ...
